sonar.projectKey=alan270987_atelier-devops-todolist
sonar.organization=alan270987
sonar.sources=.
sonar.exclusions=node_modules/**,.github/**
sonar.tests=todolist.test.js
sonar.javascript.lcov.reportPaths=coverage/lcov.info
